#Database
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: SpiralStaircase
POSTGRES_SQL_HOST: 127.0.0.1
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: machine_stock

#Server
SERVER_PORT: 9000
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: jabodav.daniel@gmail.com
EMAIL_PASSWORD: gnrtufamvnqwhtgf
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}
